import React from 'react';
import { FileText, Download, Printer, Filter, Calendar, Users, Activity } from 'lucide-react';

export default function Reports() {
  const reportTemplates = [
    { id: 1, title: 'Monthly Leave Summary', icon: Calendar, desc: 'Overview of all leaves taken in the current month across all departments.', color: 'text-blue-400', bg: 'bg-blue-500/15' },
    { id: 2, title: 'Quarterly Behavior Report', icon: Activity, desc: 'Detailed analysis of behavior scores, trends, and flagged patterns.', color: 'text-indigo-400', bg: 'bg-indigo-500/15' },
    { id: 3, title: 'Department Comparison', icon: Users, desc: 'Side-by-side comparison of leave metrics between different departments.', color: 'text-purple-400', bg: 'bg-purple-500/15' },
    { id: 4, title: 'Absenteeism Report', icon: FileText, desc: 'Ranking of employees by total absence days and unplanned leave ratio.', color: 'text-red-400', bg: 'bg-red-500/15' },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-text-main">Reports & Exports</h1>
          <p className="text-sm text-text-muted">Generate, schedule, and export HR analytics reports</p>
        </div>
        <button 
          onClick={() => alert('Custom Report Builder will open here')}
          className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700 transition-colors flex items-center gap-2"
        >
          <FileText className="w-4 h-4" />
          Custom Report Builder
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {reportTemplates.map(template => (
          <div 
            key={template.id} 
            onClick={() => alert(`Generating ${template.title}...`)}
            className="bg-bg-card p-5 rounded-xl border border-border-subtle hover:border-indigo-500/50 transition-colors cursor-pointer group"
          >
            <div className={`${template.bg} ${template.color} w-12 h-12 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
              <template.icon className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-semibold text-text-main mb-2">{template.title}</h3>
            <p className="text-sm text-text-muted mb-4 h-10 line-clamp-2">{template.desc}</p>
            <div className="flex items-center text-indigo-400 text-sm font-medium">
              Generate Report <span className="ml-1 group-hover:translate-x-1 transition-transform">→</span>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-bg-card rounded-xl border border-border-subtle overflow-hidden">
        <div className="border-b border-border-subtle px-6 py-4 flex justify-between items-center bg-bg-hover">
          <h2 className="text-lg font-semibold text-text-main">Recent Generated Reports</h2>
          <div className="flex gap-2">
            <button 
              onClick={() => alert('Filtering options...')}
              className="p-2 text-text-muted hover:text-text-main bg-bg-card border border-border-subtle rounded-lg"
            >
              <Filter className="w-4 h-4" />
            </button>
          </div>
        </div>
        
        <table className="min-w-full divide-y divide-border-subtle">
          <thead className="bg-bg-card">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">Report Name</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">Generated By</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">Date</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-text-muted uppercase tracking-wider">Format</th>
              <th className="px-6 py-3 text-right text-xs font-medium text-text-muted uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border-subtle">
            {[
              { id: 1, name: 'Q3 Behavior Analysis', by: 'Sarah Williams', date: 'Oct 15, 2023', format: 'PDF' },
              { id: 2, name: 'September Leave Summary', by: 'System (Auto)', date: 'Oct 01, 2023', format: 'Excel' },
              { id: 3, name: 'Engineering Dept Audit', by: 'John Doe', date: 'Sep 28, 2023', format: 'PDF' },
            ].map((report) => (
              <tr key={report.id} className="hover:bg-bg-hover">
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="flex items-center">
                    <FileText className={`w-5 h-5 mr-3 ${report.format === 'PDF' ? 'text-red-500' : 'text-emerald-500'}`} />
                    <span className="text-sm font-medium text-text-main">{report.name}</span>
                  </div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-text-muted">{report.by}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-text-muted">{report.date}</td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                    report.format === 'PDF' ? 'bg-red-500/15 text-red-500' : 'bg-emerald-500/15 text-emerald-500'
                  }`}>
                    {report.format}
                  </span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <button 
                    onClick={() => alert(`Downloading ${report.name}...`)}
                    className="text-indigo-400 hover:text-indigo-300 mr-3" 
                    title="Download"
                  >
                    <Download className="w-4 h-4 inline" />
                  </button>
                  <button 
                    onClick={() => alert(`Printing ${report.name}...`)}
                    className="text-text-muted hover:text-text-main" 
                    title="Print"
                  >
                    <Printer className="w-4 h-4 inline" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
